generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      City
    theme:            default
    css:             /sf/sf_admin/css/admin_main.css
    list:
            title: 'City'
            display: [name, country]
            fields:
              enablecountry: {name: Country}
              file_path:  { type: admin_input_file_tag }
            max_per_page: 10000
            object_actions:
              _edit: ~
    edit:
      title: 'Create/Edit City'
      display: [id, name, country_id]
      actions:
        _list: ~
        _save: ~
        _save_and_add: ~
    create:
      title: 'Create/Edit City'
      display: [id, name, country_id]